[package]
name = "client"
version = "0.1.0"
edition = "2024"
default-run = "aptos-setup-ceremony"

[[bin]]
name = "aptos-setup-ceremony"
path = "src/main.rs"
test = false
bench = false

[dependencies]
clap = { workspace = true }
clap_derive = { workspace = true }
common = { workspace = true }
server = { workspace = true }
rand = { workspace = true }
dirs = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
ed25519-dalek = { workspace = true }
csv = { workspace = true }
tabled.workspace = true
hex = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
bcs = { workspace = true }
rayon = { workspace = true }
bytes = { workspace = true }
aptos-batch-encryption = { workspace = true }
aptos-crypto = { workspace = true }
chrono = { workspace = true }
blake3 = { workspace = true }
bitcode = { workspace = true }


