[workspace]
resolver = "3"
members = ["common"]


[workspace.dependencies]
bcs = "0.1.6"
blake3 = { version = "1.8.3", features = ["serde"] }
ed25519-dalek = { version = "2.2.0", features = ["rand_core", "serde"] }
rand_core = "0.6.4"
rand = "0.8.5"
serde = { version = "1.0.228", features = ["derive"] }
aptos-batch-encryption = { git = "https://github.com/aptos-labs/aptos-core", branch = "main" }
aptos-crypto = { git = "https://github.com/aptos-labs/aptos-core", branch = "main" }
tokio = { version = "1.49.0", features = ["full"] }
thiserror = "2.0.18"
ark-bls12-381 = { version = "0.5.0", features = ["curve"] }
ark-bn254 = { version = "0.5.0", features = ["curve"] }
ark-ec = { version = "0.5.0", features = ["parallel", "rayon"] }
ark-ff = { version = "0.5.0", features = ["asm"] }
ark-ff-asm = { version = "0.5.0" }
ark-ff-macros = "0.5.0"
ark-poly = { version = "0.5.0", features = ["parallel"] }
ark-serialize = { version = "0.5.0", features = ["derive"] }
ark-std = { version = "0.5.0", features = ["getrandom"] }
sha2 = { version = "0.10.9", features = ["asm-aarch64", "asm"] }


[patch.crates-io]
# version 0.6 at commit 444eb13579c733089453806743b19f1ea2dce1c0 did not expose 'run_bench_with_bencher' as a public function, which we need
dudect-bencher = { git = "https://github.com/aptos-labs/dudect-bencher", rev = "9515677c83c58884c1a8c764251753269d46fc0e" }
serde-reflection = { git = "https://github.com/aptos-labs/serde-reflection", rev = "9d2374af843a4562a194529b3cadb8518d7fcd65" }
merlin = { git = "https://github.com/aptos-labs/merlin" }
ark-ec = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-ff = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-ff-macros = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-ff-asm = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-poly = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-serialize = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }

