[workspace]
resolver = "3"
members = ["client", "common", "server", "e2e-test"]

[profile.release]
debug = true


[workspace.dependencies]
common = { path = "common" }
server = { path = "server" }
client = { path = "client" }
bcs = "0.1.6"
blake3 = { version = "1.8.3", features = ["serde"] }
ed25519-dalek = { version = "2.2.0", features = ["rand_core", "serde"] }
rand_core = "0.6.4"
rand = "0.8.5"
serde = { version = "1.0.228", features = ["derive"] }
aptos-batch-encryption = { git = "https://github.com/aptos-labs/aptos-core", branch = "rex/optimize-dlog-table-size" }
aptos-crypto = { git = "https://github.com/aptos-labs/aptos-core", branch = "rex/optimize-dlog-table-size" }
aptos-dkg = { git = "https://github.com/aptos-labs/aptos-core", branch = "rex/optimize-dlog-table-size" }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "time", "chrono"] }
tokio = { version = "1.49.0", features = ["full"] }
thiserror = "2.0.18"
ark-bls12-381 = { version = "0.5.0", features = ["curve"] }
ark-bn254 = { version = "0.5.0", features = ["curve"] }
ark-ec = { version = "0.5.0", features = ["parallel", "rayon"] }
ark-ff = { version = "0.5.0", features = ["asm"] }
ark-ff-asm = { version = "0.5.0" }
ark-ff-macros = "0.5.0"
ark-poly = { version = "0.5.0", features = ["parallel"] }
ark-serialize = { version = "0.5.0", features = ["derive"] }
ark-std = { version = "0.5.0", features = ["getrandom", "parallel"] }
sha2 = { version = "0.10.9", features = ["asm-aarch64", "asm"] }
chrono = { version = "0.4.44", features = ["serde"] }
rayon = "1.11.0"
anyhow = "1.0.102"
reqwest = { version = "0.12", features = ["json"] }
gcp_auth = "0.12"
urlencoding = "2.1"
wiremock = "0.6"
async-trait = "0.1"
serde_json = "1.0"
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["full"] }
clap = { version = "4.6.0", features = ["derive"] }
clap_derive = "4.6.0"
hex = { version = "0.4.3", features = ["serde"] }
google-cloud-auth = "1.7"
google-cloud-gax = "1.8"
google-cloud-storage = "1.9"
figment = { version = "0.10", features = ["env", "toml"] }
dirs = "6.0.0"
tabled = "0.20.0"
csv = "1.4.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = { version = "1.11.1", features = ["serde"] }
tracing-appender = "0.2.4"
nanospinner = "0.3.2"

[patch.crates-io]
# version 0.6 at commit 444eb13579c733089453806743b19f1ea2dce1c0 did not expose 'run_bench_with_bencher' as a public function, which we need
dudect-bencher = { git = "https://github.com/aptos-labs/dudect-bencher", rev = "9515677c83c58884c1a8c764251753269d46fc0e" }
merlin = { git = "https://github.com/aptos-labs/merlin" }
ark-ec = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-ff = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-ff-macros = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-ff-asm = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-poly = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-serialize = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }

