db_path = "sqlite:ceremony.sqlite3?mode=rwc"
bucket_id = "dress-rehearsal"
gcp_project_id = "benchmark-zkid-circuit"
admin_verifying_key = "20a92f463d35339143f67576b86ed1f391d248bc477c8eefeac8c44389cde5af16"


