services:
  aptos-setup-ceremony-server:
    image: us-central1-docker.pkg.dev/benchmark-zkid-circuit/aptos-setup-ceremony/server:latest
    ports:
      - "8888:8888"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /test-gcs-server.json
      RUST_BACKTRACE: 1
    restart: always
    volumes:
      - "/home/rex_fernando_aptoslabs_com/test-gcs-server.json:/test-gcs-server.json:ro"
      - "./server/ceremony.sqlite3:/ceremony.sqlite3"
      - "./server/logs:/logs"

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from encrypted-mempool.setup-ceremony.aptos.dev --to aptos-setup-ceremony-server:8888
    volumes:
      - caddy_data:/data


volumes:
  caddy_data:
