services:
  aptos-setup-ceremony-server:
    image: us-central1-docker.pkg.dev/benchmark-zkid-circuit/aptos-setup-ceremony/server:latest
    ports:
      - "8888:8888"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /test-gcs-server.json
    restart: always
    volumes:
      - "/home/rex_fernando_aptoslabs_com/test-gcs-server.json:/test-gcs-server.json:ro"
      - "./server/ceremony.sqlite3:/ceremony.sqlite3"
      - "./server/logs:/logs"
  ngrok:
    image: cloudflare/cloudflared:latest
    command:
      - tunnel
      - --no-autoupdate
      - --url
      - http://aptos-setup-ceremony-server:8888
      - run
    env_file:
      - "/home/rex_fernando_aptoslabs_com/cloudflared.env"
    depends_on:
      - aptos-setup-ceremony-server
