services:
  aptos-setup-ceremony-server:
    build: .
    ports:
      - "8888:8888"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /test-gcs-server.json
    restart: always
    volumes:
      - "/home/rex_fernando_aptoslabs_com/test-gcs-server.json:/test-gcs-server.json:ro"
      - "./server/ceremony.sqlite3:/ceremony.sqlite3"
      - "./server/logs:/logs"
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://aptos-setup-ceremony-server:8888"
    env_file:
      - "/home/rex_fernando_aptoslabs_com/ngrok.env"
    ports:
      - 4040:4040
