[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common", features = ["validate"] }
chrono = { workspace = true }
rayon = { workspace = true }
ed25519-dalek = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
bcs = { workspace = true }
reqwest = { workspace = true }
gcp_auth = { workspace = true }
urlencoding = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
serde_json.workspace = true
http-body-util = "0.1.3"
google-cloud-auth = { workspace = true }
google-cloud-gax = { workspace = true }
google-cloud-storage = { workspace = true }
figment = { workspace = true }
tabled = { workspace = true }
rustls = "0.23"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rand = { workspace = true }
bytes = { workspace = true }
blake3 = { workspace = true }
tracing-appender = "0.2.4"
bitcode = { workspace = true }

[dev-dependencies]
wiremock = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
rustls = "0.23"
