[package]
name = "common"
version = "0.1.0"
edition = "2024"

[lib]


[dependencies]
bcs = { workspace = true }
blake3 = { workspace = true }
ed25519-dalek = { workspace = true }
rand_core = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
aptos-batch-encryption = { workspace = true }
aptos-crypto = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
ark-std = { workspace = true, features = ["parallel", "rayon"] }
ark-ff = { workspace = true }
ark-ff-asm = { workspace = true }
ark-ff-macros = { workspace = true }
ark-ec.workspace = true
sha2 = { workspace = true }
rayon = { workspace = true }
chrono = { workspace = true }
ark-serialize.workspace = true
ark-bls12-381.workspace = true
hex = { workspace = true }
anyhow = { workspace = true }


[[bench]]
name = "fptx"
harness = false
